### ISSUE TITLE
 ERROR - pyls_jsonrpc.endpoint - Failed to handle request 5 Traceback (most recent call last):

### ISSUE THREAD

**Issue by ENate** [krassowski/jupyterlab-lsp#105]
I installed the following packages for jupyterlab extension:+
pip install --pre jupyter-lsp
jupyter labextension install @krassowski/jupyterlab-lsp
conda install -c conda-forge python-language-server r-languageserver

but got the following error messages:

ERROR - pyls_jsonrpc.endpoint -
Traceback (most recent call last):
  File "/home/mydir/miniconda3/envs/deepl/lib/python3.6/site-pa
, line 113, in consume
    self._handle_request(message['id'], message['method'], mes
  File "/home/mydir/miniconda3/envs/deepl/lib/python3.6/site-pa
, line 182, in _handle_request
    handler_result = handler(params)
  File "/home/mydir/miniconda3/envs/deepl/lib/python3.6/site-pa
py", line 23, in handler
    return method(**(params or {}))
  File "/home/mydir/miniconda3/envs/deepl/lib/python3.6/site-pa
328, in m_text_document__hover
    return self.hover(textDocument['uri'], position)
  File "/home/mydir/miniconda3/envs/deepl/lib/python3.6/site-pa
262, in hover
    return self._hook('pyls_hover', doc_uri, position=position
  File "/home/mydir/miniconda3/envs/deepl/lib/python3.6/site-pa
153, in _hook
    return hook_handlers(config=self.config, workspace=workspa
  File "/home/mydir/.local/lib/python3.6/site-packages/pluggy/h
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/mydir/.local/lib/python3.6/site-packages/pluggy/m
c
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/mydir/.local/lib/python3.6/site-packages/pluggy/m
hookexec
    return outcome.get_result()
  File "/home/mydir/.local/lib/python3.6/site-packages/pluggy/c
lt
    raise ex[1].with_traceback(ex[2])
  File "/hone/.local/lib/python3.6/site-packages/pluggy/c
l
    result = func()
  File "/home/mydir/.local/lib/python3.6/site-packages/pluggy/m
>
    outcome = _Result.from_call(lambda: oldcall(hook, hook_imp
  File "/home/mydir/.local/lib/python3.6/site-packages/pluggy/m
    firstresult=hook.spec.opts.get("firstresult") if hook.spec
  File "/home/mydir/.local/lib/python3.6/site-packages/pluggy/c
all
    return outcome.get_result()
  File "/home/mydir/.local/lib/python3.6/site-packages/pluggy/c
lt
    raise ex[1].with_traceback(ex[2])
  File "/home/mydir/.local/lib/python3.6/site-packages/pluggy/c
all
......
But the message disappears  when I disable the jupyterlab extension in Jupyter Lab.

Any help will be welcomed.

**Comment by luminoso** [comment]
I also have this issue related with `pyls_jsonrpc.endpoint` with jupyterlab 1.2.3.

This is a clean installation
Code suggestions take long minutes to show up, if shown at all
I tried a clean jupyterlab + jupyterlab-lsp installation.

`[I 15:08:45.424 LabApp] Kernel shutdown: 976755e3-84ff-482a-9aaf-f010bcc98556
[W 15:08:46.090 LabApp] delete /Untitled1.ipynb
2019-11-26 15:08:46,803 UTC - ERROR - pyls_jsonrpc.endpoint - Failed to handle notification textDocument/didChange: {'textDocument': {'uri': 'file:///home/datas/guilherme_pipenv/Untitled1.i
pynb', 'version': 1}, 'contentChanges': [{'text': ''}]}
Traceback (most recent call last):
  File "/home/datas/.local/share/virtualenvs/guilherme_pipenv-scGX_FtN/lib/python3.6/site-packages/pyls_jsonrpc/endpoint.py", line 142, in _handle_notification
    handler_result = handler(params)
  File "/home/datas/.local/share/virtualenvs/guilherme_pipenv-scGX_FtN/lib/python3.6/site-packages/pyls_jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/home/datas/.local/share/virtualenvs/guilherme_pipenv-scGX_FtN/lib/python3.6/site-packages/pyls/python_ls.py", line 305, in m_text_document__did_change
    version=textDocument.get('version')
  File "/home/datas/.local/share/virtualenvs/guilherme_pipenv-scGX_FtN/lib/python3.6/site-packages/pyls/workspace.py", line 81, in update_document
    self._docs[doc_uri].apply_change(change)
KeyError: 'file:///home/datas/guilherme_pipenv/Untitled1.ipynb'
[W 15:08:48.436 LabApp] Notebook Untitled.ipynb is not trusted
`

**Comment by luminoso** [comment]
And right afterwards there looks like to be a different, but related, error:

```
2019-11-26 15:38:33,891 UTC - ERROR - pyls_jsonrpc.endpoint - Failed to handle request 115
Traceback (most recent call last):
  File "/home/luminoso/PycharmProjects/jupyterturbinado/venv/lib64/python3.7/site-packages/pyls_jsonrpc/endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "/home/luminoso/PycharmProjects/jupyterturbinado/venv/lib64/python3.7/site-packages/pyls_jsonrpc/endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "/home/luminoso/PycharmProjects/jupyterturbinado/venv/lib64/python3.7/site-packages/pyls_jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/home/luminoso/PycharmProjects/jupyterturbinado/venv/lib64/python3.7/site-packages/pyls/python_ls.py", line 328, in m_text_document__hover
    return self.hover(textDocument['uri'], position)
  File "/home/luminoso/PycharmProjects/jupyterturbinado/venv/lib64/python3.7/site-packages/pyls/python_ls.py", line 262, in hover
    return self._hook('pyls_hover', doc_uri, position=position) or {'contents': ''}
  File "/home/luminoso/PycharmProjects/jupyterturbinado/venv/lib64/python3.7/site-packages/pyls/python_ls.py", line 153, in _hook
    return hook_handlers(config=self.config, workspace=workspace, document=doc, **kwargs)
  File "/home/luminoso/PycharmProjects/jupyterturbinado/venv/lib64/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/luminoso/PycharmProjects/jupyterturbinado/venv/lib64/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/luminoso/PycharmProjects/jupyterturbinado/venv/lib64/python3.7/site-packages/pluggy/manager.py", line 337, in traced_hookexec
    return outcome.get_result()
  File "/home/luminoso/PycharmProjects/jupyterturbinado/venv/lib64/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/luminoso/PycharmProjects/jupyterturbinado/venv/lib64/python3.7/site-packages/pluggy/callers.py", line 52, in from_call
    result = func()
  File "/home/luminoso/PycharmProjects/jupyterturbinado/venv/lib64/python3.7/site-packages/pluggy/manager.py", line 335, in <lambda>
    outcome = _Result.from_call(lambda: oldcall(hook, hook_impls, kwargs))
  File "/home/luminoso/PycharmProjects/jupyterturbinado/venv/lib64/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/luminoso/PycharmProjects/jupyterturbinado/venv/lib64/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/luminoso/PycharmProjects/jupyterturbinado/venv/lib64/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/luminoso/PycharmProjects/jupyterturbinado/venv/lib64/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/luminoso/PycharmProjects/jupyterturbinado/venv/lib64/python3.7/site-packages/pyls/plugins/hover.py", line 12, in pyls_hover
    definitions = document.jedi_script(position).goto_definitions()
  File "/home/luminoso/PycharmProjects/jupyterturbinado/venv/lib64/python3.7/site-packages/pyls/workspace.py", line 250, in jedi_script
    return jedi.Script(**kwargs)
  File "/home/luminoso/PycharmProjects/jupyterturbinado/venv/lib64/python3.7/site-packages/jedi/api/__init__.py", line 132, in __init__
    raise ValueError('`line` parameter is not in a valid range.')
ValueError: `line` parameter is not in a valid range.
```

**Comment by yihengli** [comment]
Sometimes my jupyterlab notebook will hang. Like you execute a simple command cell, such as `print("hello")` it then took 30s to 1min to respond. When I checked the terminal, I could only find this error message. I was wondering if this error would also make the jupyterlab environment stucked untill the suggestion message actually shown up

**Comment by sentient-soellingeraj** [comment]
This seems to happen when I try to "Jump to Definition"  and it fails.
