### ISSUE TITLE
Rename method fails

### ISSUE THREAD

**Issue by andreamoro** [krassowski/jupyterlab-lsp#235]
## Description

By the time I use the rename method, I got an error

![image](https://user-images.githubusercontent.com/5256583/77894195-dc859d80-726c-11ea-8d22-8f0ee378de32.png)

## Reproduce

Either press F2 or use the context menu item and go for a symbol rename

## Context

- Operating System and version: OS X 10.15.4 Cataling
- Browser and version: Chrome 80
- JupyterLab version: 2.0.1
- `jupyter-lsp` version:
- `@krassowski/jupyterlab-lsp` version:

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
404 GET /api/kernels/aa7f4bfe-9d12-4433-be54-bf3ffa80dcea/channels?session_id=468b77ec-bd96-4c5f-a6be-dda0a5c042b7&token=0067c6fd5b84d70cb853b4194fc2148aed126f109e5fc848 (::1) 41.73ms referer=None
2020-03-30 09:56:15,860 UTC - ERROR - pyls_jsonrpc.endpoint - Failed to handle request 55
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyls_jsonrpc/endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "/usr/local/lib/python3.7/site-packages/pyls_jsonrpc/endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "/usr/local/lib/python3.7/site-packages/pyls_jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/usr/local/lib/python3.7/site-packages/pyls/python_ls.py", line 340, in m_text_document__rename
    return self.rename(textDocument['uri'], position, newName)
  File "/usr/local/lib/python3.7/site-packages/pyls/python_ls.py", line 283, in rename
    return self._hook('pyls_rename', doc_uri, position=position, new_name=new_name)
  File "/usr/local/lib/python3.7/site-packages/pyls/python_ls.py", line 155, in _hook
    return hook_handlers(config=self.config, workspace=workspace, document=doc, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.7/site-packages/pluggy/manager.py", line 337, in traced_hookexec
    return outcome.get_result()
  File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 52, in from_call
    result = func()
  File "/usr/local/lib/python3.7/site-packages/pluggy/manager.py", line 335, in <lambda>
    outcome = _Result.from_call(lambda: oldcall(hook, hook_impls, kwargs))
  File "/usr/local/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.7/site-packages/pyls/plugins/rope_rename.py", line 21, in pyls_rename
    document.offset_at_position(position)
  File "/usr/local/lib/python3.7/site-packages/rope/refactor/rename.py", line 25, in __init__
    evaluate.eval_location2(this_pymodule, offset)
  File "/usr/local/lib/python3.7/site-packages/rope/base/evaluate.py", line 19, in eval_location2
    return pyname_finder.get_primary_and_pyname_at(offset)
  File "/usr/local/lib/python3.7/site-packages/rope/base/evaluate.py", line 81, in get_primary_and_pyname_at
    holding_scope = self.module_scope.get_inner_scope_for_line(lineno)
  File "/usr/local/lib/python3.7/site-packages/rope/base/pyscopes.py", line 132, in get_inner_scope_for_line
    return self._scope_finder.get_holding_scope(self, lineno, indents)
  File "/usr/local/lib/python3.7/site-packages/rope/base/pyscopes.py", line 229, in get_holding_scope
    line_indents = self.get_indents(lineno)
  File "/usr/local/lib/python3.7/site-packages/rope/base/pyscopes.py", line 222, in get_indents
    self.lines.get_line(lineno))
  File "/usr/local/lib/python3.7/site-packages/rope/base/codeanalyze.py", line 61, in get_line
    self.starts[lineno] - 1]
IndexError: list index out of range
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
LSP: Jupyter/TaxonomySearchAPIWrapper.ipynb python connected.
jl_adapter.js:309 LSP: Adapter for Jupyter/TaxonomySearchAPIWrapper.ipynb is ready.
jl_adapter.js:178 LSP: virtual document(s) for Jupyter/TaxonomySearchAPIWrapper.ipynb have been initialized
diagnostics.js:104 Ignoring inspections silenced for this document: Array(1)
diagnostics.js:104 Ignoring inspections silenced for this document: Array(1)
diagnostics.js:104 Ignoring inspections silenced for this document: Array(1)
diagnostics.js:104 Ignoring inspections silenced for this document: Array(1)
cm_adapter.js:27 No change obtained from CodeMirror editor within the expected time of 0.66s
DevTools failed to parse SourceMap: file:///Users/andreamoro/Library/Application%20Support/Google/Chrome/Default/Extensions/aeblfdkhhhdcdjpifhhbdiojplfjncoa/1.18.0_0/inline/injected.js.map
</pre>
</details>

**Comment by krassowski** [comment]
Thank you for opening this issue. Please provide a full reproducible example with minimal code needed to trigger this message. This error is known to show up when there is a syntax error in the code (which is an issue of the language server, not this extension by the way), however, it should have been replaced with a nicer message - I will investigate if you can provide more details.

**Comment by andreamoro** [comment]
Hi, 
Have been working on an internal API without a chance to make it reproducible outside at present.

But it doesn't seem to be the only error. 
The Jump to Definition doesn't work too.

But the code compiles as I'm using it.

**Comment by masip85** [comment]
![image](https://user-images.githubusercontent.com/12863854/82162835-abf2d500-98a7-11ea-838f-25d23cd7fd06.png)
if in previous cells you can see in image there is any syntax error, when you rename, even if it's unrelated, error appears. If you correct that syntax error, rename works fine.

**Comment by krassowski** [comment]
@andreamoro I would need to see your notebook to be able to help more. If the error persists in the new version 2.0 (to be released today) please reopen with a reproducible example.

@masip85 thanks for providing an example, this is indeed as expected.The limitations of rename are not due to errors in this extension but because of how it is implemented in the python-language-server (pyls). If you wish you could try using another language server for Python (e.g. pylance) which may handle it better, or open an issue in the pyls repository. Thanks!
