### ISSUE TITLE
Installation issues, am i using the right versions?

### ISSUE THREAD

**Issue by chenbr** [krassowski/jupyterlab-lsp#248]
## Description

Running into a installation issue in build...

## Reproduce

    jupyter labextension install @krassowski/jupyterlab-lsp@0.8.0

## Context

- Operating System and version:
- Browser and version: chrome Version 79.0.3945.130 (Official Build) (64-bit)
- JupyterLab version: 0.35.4
- `jupyter-lsp` version: 0.8.0
- `@krassowski/jupyterlab-lsp` version: 0.8.0

<details><summary>Troubleshoot Output</summary>
<pre>
> /opt/conda/bin/npm pack @krassowski/jupyterlab-lsp@0.8.0
krassowski-jupyterlab-lsp-0.8.0.tgz
Node v8.10.0

The extension "nbdime-jupyterlab" is outdated.

> node /opt/conda/lib/python3.6/site-packages/jupyterlab/staging/yarn.js install
yarn install v1.9.4
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning @jupyterlab/application > @jupyterlab/coreutils > comment-json > json-parser@1.1.5: `json-parser` is deprecated. Please use `comment-json` instead
warning @jupyterlab/application > @jupyterlab/apputils > react-dom > fbjs > core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning @jupyterlab/faq-extension@0.19.1: The JupyterLab FAQ extension is no longer developed and is removed from JupyterLab 1.0.
warning @jupyterlab/json-extension > react-json-tree > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning @krassowski/jupyterlab-lsp > @krassowski/jupyterlab_go_to_definition > @jupyterlab/application > @jupyterlab/ui-components > @blueprintjs/core > popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
warning @krassowski/jupyterlab-lsp > @krassowski/jupyterlab_go_to_definition > @jupyterlab/application > @jupyterlab/ui-components > @blueprintjs/core > react-popper > popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
warning css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning webpack > watchpack > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning webpack > watchpack > chokidar > fsevents@1.2.12: fsevents 1 will break on node v14+. Upgrade to fsevents 2 with massive improvements.
warning webpack > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning webpack > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
[3/5] Fetching packages...
warning vscode-languageclient@5.2.1: The engine "vscode" appears to be invalid.
info fsevents@1.2.12: The platform "linux" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "@jupyterlab/vdom-extension > @nteract/transform-vdom@1.1.1" has incorrect peer dependency "react@^15.6.1".
warning "@jupyterlab/vega4-extension > vega-embed > vega-themes@2.8.3" has unmet peer dependency "vega@*".
warning "@jupyterlab/vega4-extension > vega-embed > vega-lite@2.7.0" has unmet peer dependency "vega@^3.0.0 || ^4.0.0".
warning " > @krassowski/jupyterlab-lsp@0.8.0" has incorrect peer dependency "@jupyterlab/application@^1.1".
warning " > @krassowski/jupyterlab-lsp@0.8.0" has incorrect peer dependency "@jupyterlab/apputils@^1.1".
warning " > @krassowski/jupyterlab-lsp@0.8.0" has incorrect peer dependency "@jupyterlab/cells@^1.1".
warning " > @krassowski/jupyterlab-lsp@0.8.0" has incorrect peer dependency "@jupyterlab/codeeditor@^1.1".
warning " > @krassowski/jupyterlab-lsp@0.8.0" has incorrect peer dependency "@jupyterlab/codemirror@^1.1".
warning " > @krassowski/jupyterlab-lsp@0.8.0" has incorrect peer dependency "@jupyterlab/completer@^1.1".
warning " > @krassowski/jupyterlab-lsp@0.8.0" has incorrect peer dependency "@jupyterlab/coreutils@^3.1".
warning " > @krassowski/jupyterlab-lsp@0.8.0" has incorrect peer dependency "@jupyterlab/docmanager@^1.1".
warning " > @krassowski/jupyterlab-lsp@0.8.0" has incorrect peer dependency "@jupyterlab/docregistry@^1.1".
warning " > @krassowski/jupyterlab-lsp@0.8.0" has incorrect peer dependency "@jupyterlab/fileeditor@^1.1".
warning " > @krassowski/jupyterlab-lsp@0.8.0" has incorrect peer dependency "@jupyterlab/notebook@^1.1".
warning " > @krassowski/jupyterlab-lsp@0.8.0" has incorrect peer dependency "@jupyterlab/rendermime@^1.1".
warning " > @krassowski/jupyterlab-lsp@0.8.0" has incorrect peer dependency "@jupyterlab/services@^4.1".
warning " > @krassowski/jupyterlab-lsp@0.8.0" has unmet peer dependency "@jupyterlab/statusbar@^1.1".
warning " > @krassowski/jupyterlab-lsp@0.8.0" has unmet peer dependency "@jupyterlab/testutils@^1.2.2".
warning " > @krassowski/jupyterlab-lsp@0.8.0" has incorrect peer dependency "@jupyterlab/tooltip@^1.1".
warning "@krassowski/jupyterlab-lsp > @krassowski/jupyterlab_go_to_definition > @jupyterlab/services > ws@7.2.3" has unmet peer dependency "bufferutil@^4.0.1".
warning "@krassowski/jupyterlab-lsp > @krassowski/jupyterlab_go_to_definition > @jupyterlab/services > ws@7.2.3" has unmet peer dependency "utf-8-validate@^5.0.2".
warning "@krassowski/jupyterlab-lsp > @krassowski/jupyterlab_go_to_definition > @jupyterlab/application > @jupyterlab/ui-components@1.2.1" has incorrect peer dependency "react@~16.8.4".
[5/5] Building fresh packages...
success Saved lockfile.
Done in 31.70s.
> node /opt/conda/lib/python3.6/site-packages/jupyterlab/staging/yarn.js run build
yarn run v1.9.4
$ webpack
ModuleNotFoundError: Module not found: Error: Can't resolve '@jupyterlab/ui-components' in '/opt/conda/share/jupyter/lab/staging/node_modules/@krassowski/jupyterlab-lsp/lib/adapters/jupyterlab/components'
    at factory.create (/opt/conda/share/jupyter/lab/staging/node_modules/webpack/lib/Compilation.js:535:10)
    at factory (/opt/conda/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
    at resolver (/opt/conda/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/opt/conda/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /opt/conda/share/jupyter/lab/staging/node_modules/neo-async/async.js:2830:7
    at /opt/conda/share/jupyter/lab/staging/node_modules/neo-async/async.js:6877:13
    at normalResolver.resolve (/opt/conda/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/opt/conda/share/jupyter/lab/staging/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:213:14)
    at hook.callAsync (/opt/conda/share/jupyter/lab/staging/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/opt/conda/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at resolver.doResolve (/opt/conda/share/jupyter/lab/staging/node_modules/webpack/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7)
    at hook.callAsync (/opt/conda/share/jupyter/lab/staging/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/opt/conda/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at hook.callAsync (/opt/conda/share/jupyter/lab/staging/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/opt/conda/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at resolver.doResolve (/opt/conda/share/jupyter/lab/staging/node_modules/webpack/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43)
    at hook.callAsync (/opt/conda/share/jupyter/lab/staging/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn41 (eval at create (/opt/conda/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)
    at resolver.doResolve (/opt/conda/share/jupyter/lab/staging/node_modules/webpack/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:30:40)
    at hook.callAsync (/opt/conda/share/jupyter/lab/staging/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/opt/conda/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at hook.callAsync (/opt/conda/share/jupyter/lab/staging/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/opt/conda/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at args (/opt/conda/share/jupyter/lab/staging/node_modules/webpack/node_modules/enhanced-resolve/lib/forEachBail.js:30:14)
    at hook.callAsync (/opt/conda/share/jupyter/lab/staging/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/opt/conda/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at resolver.doResolve (/opt/conda/share/jupyter/lab/staging/node_modules/webpack/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7)
    at hook.callAsync (/opt/conda/share/jupyter/lab/staging/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/opt/conda/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at hook.callAsync (/opt/conda/share/jupyter/lab/staging/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
resolve '@jupyterlab/ui-components' in '/opt/conda/share/jupyter/lab/staging/node_modules/@krassowski/jupyterlab-lsp/lib/adapters/jupyterlab/components'
  Parsed request is a module
  using description file: /opt/conda/share/jupyter/lab/staging/node_modules/@krassowski/jupyterlab-lsp/package.json (relative path: ./lib/adapters/jupyterlab/components)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /opt/conda/share/jupyter/lab/staging/node_modules/@krassowski/jupyterlab-lsp/lib/adapters/jupyterlab/components/node_modules doesn't exist or is not a directory
      /opt/conda/share/jupyter/lab/staging/node_modules/@krassowski/jupyterlab-lsp/lib/adapters/jupyterlab/node_modules doesn't exist or is not a directory
      /opt/conda/share/jupyter/lab/staging/node_modules/@krassowski/jupyterlab-lsp/lib/adapters/node_modules doesn't exist or is not a directory
      /opt/conda/share/jupyter/lab/staging/node_modules/@krassowski/jupyterlab-lsp/lib/node_modules doesn't exist or is not a directory
      /opt/conda/share/jupyter/lab/staging/node_modules/@krassowski/jupyterlab-lsp/node_modules doesn't exist or is not a directory
      /opt/conda/share/jupyter/lab/staging/node_modules/@krassowski/node_modules doesn't exist or is not a directory
      /opt/conda/share/jupyter/lab/staging/node_modules/node_modules doesn't exist or is not a directory
      /opt/conda/share/jupyter/lab/node_modules doesn't exist or is not a directory
      /opt/conda/share/jupyter/node_modules doesn't exist or is not a directory
      /opt/conda/share/node_modules doesn't exist or is not a directory
      /opt/conda/node_modules doesn't exist or is not a directory
      /opt/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /opt/conda/share/jupyter/lab/staging/node_modules
        using description file: /opt/conda/share/jupyter/lab/staging/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: /opt/conda/share/jupyter/lab/staging/package.json (relative path: ./node_modules/@jupyterlab/ui-components)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /opt/conda/share/jupyter/lab/staging/node_modules/@jupyterlab/ui-components doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              /opt/conda/share/jupyter/lab/staging/node_modules/@jupyterlab/ui-components.wasm doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /opt/conda/share/jupyter/lab/staging/node_modules/@jupyterlab/ui-components.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /opt/conda/share/jupyter/lab/staging/node_modules/@jupyterlab/ui-components.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /opt/conda/share/jupyter/lab/staging/node_modules/@jupyterlab/ui-components.json doesn't exist
            as directory
              /opt/conda/share/jupyter/lab/staging/node_modules/@jupyterlab/ui-components doesn't exist
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by krassowski** [comment]
Hi @chenbr, thanks for opening this issue. You have a very old JupyterLab version installed (0.35.4), which is no longer supported. You may want to try:

- @krassowski/jupyterlab-lsp@0.8.0 with JupyterLab 1.x
- @krassowski/jupyterlab-lsp with JupyterLab 2.x

I highly recommend upgrading to JupyterLab 2.x!

**Comment by krassowski** [comment]
I hope it worked ok for you! Closing due to lack of activity - please feel free to reopen if you have any other questions or feedback :)
