### ISSUE TITLE
KeyError when opening new notebook

### ISSUE THREAD

**Issue by jarutis** [krassowski/jupyterlab-lsp#33]
I followed the steps outlined in readme, but it seems that pyls can't find source files I get this error:

```
Example Server: 2019-09-12 10:35:37,818 UTC - ERROR - pyls_jsonrpc.endpoint - Failed to handle notification textDocument/didChange: {'textDocument': {'uri': 'file:///test.ipynb.python', 'version': 1}, 'contentChanges': [{'text': 'import pandas as pd\n\n\npd.\n'}]}
Traceback (most recent call last):                                                                                                                                                                                    File "/usr/local/miniconda3/envs/notebook/lib/python3.7/site-packages/pyls_jsonrpc/endpoint.py", line 142, in _handle_notification
    handler_result = handler(params)
  File "/usr/local/miniconda3/envs/notebook/lib/python3.7/site-packages/pyls_jsonrpc/dispatchers.py", line 23, in handler                                                                                               return method(**(params or {}))
  File "/usr/local/miniconda3/envs/notebook/lib/python3.7/site-packages/pyls/python_ls.py", line 281, in m_text_document__did_change
    version=textDocument.get('version')                                                                                                                                                                               File "/usr/local/miniconda3/envs/notebook/lib/python3.7/site-packages/pyls/workspace.py", line 77, in update_document
    self._docs[doc_uri].apply_change(change)
KeyError: 'file:///test.ipynb.python'
```

**Comment by jarutis** [comment]
So it seems that it works if the notebook is in the same directory where I start Jupyter Lab, but not in subfolders.

![errors](https://uce9b6ce035146e99edd03dd4200.previews.dropboxusercontent.com/p/thumb/AAifDfNGg8mJaPtaDY_TwAnURWL1cZ_DpkRjcBvi0YwEN_PVdmPiDTXpN38zhVG-o8gIHR-iWVxmWxm_0cj1jsVxtw53olEXcUq9tgL8fShYZA7UKGsQ9T_6RPuca80WofxZ_V3IynNRxieEUgSQ7jObCJ45q2mjDCa4inPQiUZymQitkNFxLYLRNhVIcb53S9e8k685EaK825g0gKEnDBFK8rE4cPmJimkFqQhu39JPcDa8xRNm_QPZit3VBJ-0a_Jy_9HppvfnUkezl1pI2rNBBiAhkvGdXjoL_Kej-OZcGtTg3p11mC3KiSKfq-djpS9Leu-jo4OWyZZj64B9gVD6Ox2tIFHcqTxuZDZGWTZUSSv39UAglo7jauL1XrZ0D1Vk53SAa1Y6VkFdf7xuYjZJeO0RUPY_8LoqmFMXbc-ovnxogs4hGLsA_B0pMwDa_Akr4S6HX8Y22kDe92ZxTATlogztb1xZo97_t2M2OW99uA/p.png?fv_content=true&size_mode=5)

**Comment by jarutis** [comment]
Same error pops up if I create subfolder in a Binder example in the repo.

<img width="648" alt="Screenshot 2019-09-16 10 19 49" src="https://user-images.githubusercontent.com/3201415/64940073-b4ec5c00-d86b-11e9-8ecf-cbe57e35ae8e.png">

**Comment by krassowski** [comment]
Thank you. I am able to see this message - this comes from the pyls LSP server; this error - as far as I know - is nothing serious to worry about right now, as the absolute path handling is yet to be implemented.

The extension otherwise works as expected (see the underline of trailing spaces, and the ctrl+hover action displaying a tooltip on the screenshot below - with the paths reproducing your test scenario on binder). Could you confirm that it works for you as well?

![works_ok](https://user-images.githubusercontent.com/5832902/64953489-dacd2d00-d87a-11e9-9cbf-272c97d57294.png)

**Comment by krassowski** [comment]
Hi! There were a lot of changes under the hood recently - could you confirm if you still see this problem?

**Comment by jarutis** [comment]
I do not see the error. Closing.

**Comment by shreyasgm** [comment]
Hi, thank you for your work on this extension. I think this error might have resurfaced - I'm getting the following error on two separate machines:

```
2019-11-01 08:49:54,265 UTC - ERROR - pyls_jsonrpc.endpoint - Failed to handle notification textDocument/didChange: {u'contentChanges': [{u'text': <text_hidden>}], u'textDocument': {u'version': 0, u'uri': u'file:///Users/shg309/<path_hidden>.ipynb'}}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pyls_jsonrpc/endpoint.py", line 142, in _handle_notification
    handler_result = handler(params)
  File "/usr/local/lib/python2.7/site-packages/pyls_jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/usr/local/lib/python2.7/site-packages/pyls/python_ls.py", line 279, in m_text_document__did_change
    version=textDocument.get('version')
  File "/usr/local/lib/python2.7/site-packages/pyls/workspace.py", line 77, in update_document
    self._docs[doc_uri].apply_change(change)
KeyError: u'file:///Users/shg309/<path_hidden>.ipynb'
```

**Comment by krassowski** [comment]
Thank you. It's just that pyls was not written with supporting notebooks in mind, if the extension otherwise works as expected then there is nothing to worry about (right now) - please treat it as a false positive, unless you experience other issues (i.e. some functionalities we already support not working as expected).

I will work on fixing this message later on.
