### ISSUE TITLE
Sometimes autocompletion fails with  'NoneType' object is not subscriptable` 

### ISSUE THREAD

**Issue by joelostblom** [krassowski/jupyterlab-lsp#383]
Sometimes when I try autocompletion (both with continuous mode and by pressing tab) nothing shows up and I sett this error in terminal `TypeError: 'NoneType' object is not subscriptable` (full traceback below). This has happened to me with both pandas and altair, and here is a video of it occuring when I import Altair (you can also see some slowness in the beginning as reported in #272, vscode is instant for me).

![output](https://user-images.githubusercontent.com/4560057/96165324-51e75180-0ed1-11eb-9fd0-411b23c09216.gif)

```
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/home/joel/miniconda3/envs/531/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 268, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/home/joel/miniconda3/envs/531/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/home/joel/miniconda3/envs/531/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/home/joel/miniconda3/envs/531/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 583, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/home/joel/miniconda3/envs/531/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 360, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/home/joel/miniconda3/envs/531/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 385, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/home/joel/.local/lib/python3.7/site-packages/IPython/core/completer.py", line 485, in rectify_completions
    completions = list(completions)
  File "/home/joel/.local/lib/python3.7/site-packages/IPython/core/completer.py", line 1808, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/home/joel/.local/lib/python3.7/site-packages/IPython/core/completer.py", line 1852, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "/home/joel/.local/lib/python3.7/site-packages/IPython/core/completer.py", line 1976, in _complete
    text = self.splitter.split_line(line_buffer, cursor_pos)
  File "/home/joel/.local/lib/python3.7/site-packages/IPython/core/completer.py", line 563, in split_line
    l = line if cursor_pos is None else line[:cursor_pos]
TypeError: 'NoneType' object is not subscriptable
```

## Context

The same as in https://github.com/krassowski/jupyterlab-lsp/issues/382

**Comment by krassowski** [comment]
You seem to be using an old IPython version (6.5). Could it be that you are looking at a bug https://github.com/ipython/ipython/issues/11508 which was fixed in IPython 7.15?

In any case, many thanks the detailed reports :)

**Comment by joelostblom** [comment]
Thanks for the quick response! That seems to be it. I didn't have ipython installed in this environment before doing `conda install -c conda-forge jupyter-lsp-python` so maybe the requirements for the conda package needs updating?

**Comment by krassowski** [comment]
It does not look like that. We do not require IPython directly in the conda recipe (it is a dependency of JupyterLab); [on conda-forge CI](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=206254&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=919) IPython 7.18.1-py38h1cdfbd6_0 gets installed. Not sure what could have caused that you have an old version. Are you certian that you did not have IPython installed before?

**Comment by joelostblom** [comment]
You're correct, sorry about that. I forgot that I installed `ipykernel` to be able to reach this env from my notebook env. Apparently `ipykernel` installs version 5.8 of `ipython`, which seems to be mostly of archaeological value... I have updatd my env file to require an explicit version of IPython and it works fine with `ipykernel` as well, thanks!
