### ISSUE TITLE
Fails on Python older than 3.8

### ISSUE THREAD

**Issue by krassowski** [krassowski/jupyterlab-lsp#426]
The CI tests started failing on versions of Python lower than 3.8. Needs investigation.

```python
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/jupyterlab-lsp/lib/python3.6/site-packages/jsonschema/__init__.py", line 31, in <module>
    from importlib import metadata
ImportError: cannot import name 'metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/miniconda/envs/jupyterlab-lsp/lib/python3.6/site-packages/importlib_metadata/_compat.py", line 8, in <module>
    from typing import Protocol
ImportError: cannot import name 'Protocol'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/miniconda/envs/jupyterlab-lsp/lib/python3.6/site-packages/jupyterlab_server/server.py", line 20, in <module>
    from notebook.notebookapp import aliases, flags, NotebookApp as ServerApp
  File "/usr/share/miniconda/envs/jupyterlab-lsp/lib/python3.6/site-packages/notebook/notebookapp.py", line 85, in <module>
    from .services.contents.manager import ContentsManager
  File "/usr/share/miniconda/envs/jupyterlab-lsp/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 17, in <module>
    from nbformat import sign, validate as validate_nb, ValidationError
  File "/usr/share/miniconda/envs/jupyterlab-lsp/lib/python3.6/site-packages/nbformat/__init__.py", line 32, in <module>
    from .validator import validate, ValidationError
  File "/usr/share/miniconda/envs/jupyterlab-lsp/lib/python3.6/site-packages/nbformat/validator.py", line 12, in <module>
    from .json_compat import get_current_validator, ValidationError
  File "/usr/share/miniconda/envs/jupyterlab-lsp/lib/python3.6/site-packages/nbformat/json_compat.py", line 10, in <module>
    import jsonschema
  File "/usr/share/miniconda/envs/jupyterlab-lsp/lib/python3.6/site-packages/jsonschema/__init__.py", line 33, in <module>
    import importlib_metadata as metadata
  File "/usr/share/miniconda/envs/jupyterlab-lsp/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 15, in <module>
    from ._compat import (
  File "/usr/share/miniconda/envs/jupyterlab-lsp/lib/python3.6/site-packages/importlib_metadata/_compat.py", line 15, in <module>
    from typing_extensions import Protocol  # type: ignore
ModuleNotFoundError: No module named 'typing_extensions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/miniconda/envs/jupyterlab-lsp/bin/jlpm", line 6, in <module>
    from jupyterlab.jlpmapp import main
  File "/usr/share/miniconda/envs/jupyterlab-lsp/lib/python3.6/site-packages/jupyterlab/jlpmapp.py", line 9, in <module>
    from jupyterlab_server.process import which, subprocess
  File "/usr/share/miniconda/envs/jupyterlab-lsp/lib/python3.6/site-packages/jupyterlab_server/__init__.py", line 4, in <module>
    from .app import LabServerApp
  File "/usr/share/miniconda/envs/jupyterlab-lsp/lib/python3.6/site-packages/jupyterlab_server/app.py", line 9, in <module>
    from .server import ServerApp
  File "/usr/share/miniconda/envs/jupyterlab-lsp/lib/python3.6/site-packages/jupyterlab_server/server.py", line 26, in <module>
    from jupyter_server.base.handlers import (                          # noqa
ModuleNotFoundError: No module named 'jupyter_server'

```

It seems that jsonschema is the one of the culprits:

https://stackoverflow.com/questions/59216175/importerror-cannot-import-name-metadata-from-importlib

but it's the `ModuleNotFoundError: No module named 'jupyter_server'` that worries me. It seems that we are not the issue but on the receiving end. Could it be something upstream - does it sound familiar @bollwyvl?

**Comment by krassowski** [comment]
Is it maybe missing `typing_extensions` as a requirement for older Python versions?

**Comment by bollwyvl** [comment]
Welp, we have `importlib_metadata`, which is indeed a dependency of `jsonschema`: https://github.com/krassowski/jupyterlab-lsp/runs/1549511701#step:6:98

But that hasn't changed in a while...

**Comment by krassowski** [comment]
I do not like that there is both `importlib_metadata` and `importlib-metadata`. Both were updated 5 hours ago and it would match when the thing stopped working (but it might be the conda-forge packaging issue):
https://anaconda.org/conda-forge/importlib_metadata/
https://anaconda.org/conda-forge/importlib-metadata

**Comment by krassowski** [comment]
How can I find out where `importlib-metadata` comes from on CI?

**Comment by bollwyvl** [comment]
> I do not like that there is both

Yeah, it happens. One is a `noarch` that just depends on the other one. I don't know why it was done, i guess some people really like the `pip` name to be available, while the `-` is more common in conda-land. They always get released in lock-step.

The upstream did add a dependency:

https://github.com/python/importlib_metadata/blame/6955586a940f6bfda0c662039f4c7b7cc0876c9e/setup.cfg#L22

Just opened a PR to add it:

https://github.com/conda-forge/importlib_metadata-feedstock/pull/55

As for the jlpm thing: yeah, dunno... it's basically to get the windows-aware version of `shutil.which`.

**Comment by bollwyvl** [comment]
Also made a request to mark that package as broken: https://github.com/conda-forge/admin-requests/pull/203

**Comment by bollwyvl** [comment]
Oh, the jlpm thing is probably `importlib_metadata` _also_ failing.

https://github.com/jupyterlab/jupyterlab_server/blob/1.2.0/jupyterlab_server/server.py#L25

Anyhow.... I don't _think_ we'll need to merge this PR/do another release, etc.

**Comment by krassowski** [comment]
Thanks for the work on conda side, re-running https://github.com/krassowski/jupyterlab-lsp/actions/runs/420501764 to see if we are fine for now.

**Comment by krassowski** [comment]
Something is wrong... We are still failing and the checksums are the same for both the broken package from 6 hours ago and the update from 1 hour ago:

https://anaconda.org/conda-forge/importlib_metadata/files
https://anaconda.org/conda-forge/importlib-metadata/files

unless those do not account for config which would be strange....

Edit: the checksums from a different version released 21 days ago is also the same. I may not understand how these work or something is quite wrong...

**Comment by krassowski** [comment]
Anyways it seems to be passing now. Maybe I triggered the build to early. Thank you again!
