### ISSUE TITLE
"OSError: [Errno 22] Invalid argument" just after strarting a Julia kernel

### ISSUE THREAD

**Issue by goryntsev** [krassowski/jupyterlab-lsp#608]
I am trying to start using jupyterlab-lsp with Julia language server. So far I have managed to install the lsp extension and the language server. In the status bar of my julia kernel notebooks I see that the server is "fully connected & initialized".
But in the terminal where I started the jupyter lab I receive a series of error messages like this:
<pre>
[I 2021-05-26 13:42:46.182 ServerApp] Kernel started: 40f06a6e-bb6c-4fa5-a247-22184979e277
Starting kernel event loops.
[I 2021-05-26 13:43:00.152 ServerApp] Adapting from protocol version 5.0 (kernel 40f06a6e-bb6c-4fa5-a247-22184979e277) to 5.3 (client).

[E 2021-05-26 13:43:03.213 ServerApp] <LspStdIoWriter(parent=<LanguageServerSession(language_server=julia-language-server, argv=['C:\\Users\\alexa\\AppData\\Local\\Programs\\Julia-1.6.1\\bin\\julia.EXE', '--project=.', '-e', 'using LanguageServer, LanguageServer.SymbolServer; runserver()', '.'])>)> couldn't write message: Content-Length: 186

    {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///c:/Users/alexa/.virtual_documents/Untitled5.ipynb","languageId":"julia","text":"","version":0}}}
    Traceback (most recent call last):
      File "C:\Users\alexa\miniconda3\envs\py38\lib\site-packages\jupyter_lsp\stdio.py", line 193, in write
        await convert_yielded(self._write_one(response.encode("utf-8")))
      File "C:\Users\alexa\miniconda3\envs\py38\lib\concurrent\futures\thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "C:\Users\alexa\miniconda3\envs\py38\lib\site-packages\jupyter_lsp\stdio.py", line 201, in _write_one
        self.stream.write(message)
    OSError: [Errno 22] Invalid argument

[E 2021-05-26 13:43:03.219 ServerApp] <LspStdIoWriter(parent=<LanguageServerSession(language_server=julia-language-server, argv=['C:\\Users\\alexa\\AppData\\Local\\Programs\\Julia-1.6.1\\bin\\julia.EXE', '--project=.', '-e', 'using LanguageServer, LanguageServer.SymbolServer; runserver()', '.'])>)> couldn't write message: Content-Length: 188

    {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"textDocument":{"uri":"file:///c:/Users/alexa/.virtual_documents/Untitled5.ipynb","version":0},"contentChanges":[{"text":""}]}}
    Traceback (most recent call last):
      File "C:\Users\alexa\miniconda3\envs\py38\lib\site-packages\jupyter_lsp\stdio.py", line 193, in write
        await convert_yielded(self._write_one(response.encode("utf-8")))
      File "C:\Users\alexa\miniconda3\envs\py38\lib\concurrent\futures\thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "C:\Users\alexa\miniconda3\envs\py38\lib\site-packages\jupyter_lsp\stdio.py", line 201, in _write_one
        self.stream.write(message)
    OSError: [Errno 22] Invalid argument
</pre>

And no functionality of lsp is working as if it does not exist.

**What could I tweak to make in work?**

I am on Windows 10 with Julia 1.6.1 and python 38 + jupyterlab 3.0.14 in a conda environment.

**Comment by bollwyvl** [comment]
Please check the [issue template](https://raw.githubusercontent.com/krassowski/jupyterlab-lsp/master/.github/ISSUE_TEMPLATE/bug_report.md)... there is a lot more information we could use to help you down in the context part, but there's not quite enough information in what i see there.

**Comment by goryntsev** [comment]
Sorry, please find the updated description above.

**Comment by krassowski** [comment]
> Set '"continuousHinting": true' in Settings.

does it work when you do not do that (i.e. the setting is set to false)?

What is your version of LanguageServer, SymbolServer, and JSONRPC?

**Comment by krassowski** [comment]
Also what is your Julia version.

**Comment by krassowski** [comment]
> julia language server are installed using conda

I did not know it is on conda. Do you have a link for convenience?

**Comment by goryntsev** [comment]
Sorry for my writing, I did not mean that julia language server is installed using conda —  it is my mistake in description. Certainly it has been installed as a julia package.

My julia environment:
- Julia 1.6.1
- LanguageServer v3.2.0
- IJulia v1.23.2
- SymbolServer v5.1.1 —  installed as a dependency
- JSONRPC v1.3.3 —  installed as a dependency

By the way I have tried to replicate the issue out of any conda environment, installed everything with pip —  the result is the same: sometimes it works fine for a while and then breaks with error messages anyway. This delay is particularly weird.

Setting  `"continuousHinting": false'` brings no improvement: the same behavior with the same error messages.

**Comment by krassowski** [comment]
Why don't you try updating to the most recent versions? LanguageServer v4.0.0 (and SymbolServer v7.0.0) just got released 3 hours ago.

**Comment by krassowski** [comment]
I just tested manually on Ubuntu that all works fine with IJulia v1.23.2, LanguageServer v4.0.0, and Julia 1.5.3. If after upgrade you still experience issues, please try opening an issue in https://github.com/julia-vscode/LanguageServer.jl and linking this one (providing the Julia backtrace starting with `[ Info: Received new data from Julia Symbol Server`).

**Comment by krassowski** [comment]
Could you please try to upgrade to [v3.7.0](https://github.com/krassowski/jupyterlab-lsp/releases/tag/v3.7.0) and see if it still happens?

**Comment by goryntsev** [comment]
First I followed your advice and updated the freshly relleased julia LanguageServer to v4.0.0. And again got the error messages both from the server and from the extension —  but this time they differed from those before, find an excerpt from the longer backtrace in details below.

<details><summary>backtrace with LS v4.0.0</summary>
<pre>
ERROR: get_offset crashed. More diagnostics:
line=35
character=0
position(io)=0
line_offsets='[0, 15, 16, 17, 76, 77, 78, 97, 98, 99, 134, 216, 299, 328, 360, 368, 377, 378, 379, 391, 392, 393, 435, 470, 498, 538, 604, 630, 632, 633, 634, 734, 832, 845]'
text='aaaaaaaaaaaaaa


aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa


aaaaaaaaaaaaaaaaaa


aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaa
aaaaaaaa


aaaaaaaaaaa


aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaa
a


aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaαααααααaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaαααααααaaaa
aaaaaaaaaaaa
'

original_error=ERROR: BoundsError: attempt to access 34-element Vector{Int64} at index [36]
Stacktrace:
  [1] getindex
    @ .\array.jl:801 [inlined]
  [2] get_offset(doc::LanguageServer.Document, line::Int64, character::Int64)
    @ LanguageServer C:\Users\alexa\.julia\packages\LanguageServer\jiDTR\src\document.jl:77
  [3] get_offset
    @ C:\Users\alexa\.julia\packages\LanguageServer\jiDTR\src\document.jl:98 [inlined]
  [4] textDocument_documentHighlight_request(params::LanguageServer.DocumentHighlightParams, server::LanguageServerInstance, conn::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint})
    @ LanguageServer C:\Users\alexa\.julia\packages\LanguageServer\jiDTR\src\requests\highlight.jl:3
  [5] (::LanguageServer.var"#96#97"{typeof(LanguageServer.textDocument_documentHighlight_request), LanguageServerInstance})(conn::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, params::LanguageServer.DocumentHighlightParams)
    @ LanguageServer C:\Users\alexa\.julia\packages\LanguageServer\jiDTR\src\languageserverinstance.jl:245
  [6] dispatch_msg(x::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, dispatcher::JSONRPC.MsgDispatcher, msg::Dict{String, Any})
    @ JSONRPC C:\Users\alexa\.julia\packages\JSONRPC\yu0G3\src\typed.jl:67
  [7] run(server::LanguageServerInstance)
    @ LanguageServer C:\Users\alexa\.julia\packages\LanguageServer\jiDTR\src\languageserverinstance.jl:353
  [8] runserver(pipe_in::Base.PipeEndpoint, pipe_out::Base.PipeEndpoint, env_path::String, depot_path::String, err_handler::Nothing, symserver_store_path::Nothing)
    @ LanguageServer C:\Users\alexa\.julia\packages\LanguageServer\jiDTR\src\runserver.jl:46
  [9] runserver()
    @ LanguageServer C:\Users\alexa\.julia\packages\LanguageServer\jiDTR\src\runserver.jl:44
 [10] top-level scope
    @ none:1

Stacktrace:
 [1] get_offset(doc::LanguageServer.Document, line::Int64, character::Int64)
   @ LanguageServer C:\Users\alexa\.julia\packages\LanguageServer\jiDTR\src\document.jl:95
 [2] get_offset
   @ C:\Users\alexa\.julia\packages\LanguageServer\jiDTR\src\document.jl:98 [inlined]
 [3] textDocument_documentHighlight_request(params::LanguageServer.DocumentHighlightParams, server::LanguageServerInstance, conn::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint})
   @ LanguageServer C:\Users\alexa\.julia\packages\LanguageServer\jiDTR\src\requests\highlight.jl:3
 [4] (::LanguageServer.var"#96#97"{typeof(LanguageServer.textDocument_documentHighlight_request), LanguageServerInstance})(conn::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, params::LanguageServer.DocumentHighlightParams)
   @ LanguageServer C:\Users\alexa\.julia\packages\LanguageServer\jiDTR\src\languageserverinstance.jl:245
 [5] dispatch_msg(x::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, dispatcher::JSONRPC.MsgDispatcher, msg::Dict{String, Any})
   @ JSONRPC C:\Users\alexa\.julia\packages\JSONRPC\yu0G3\src\typed.jl:67
 [6] run(server::LanguageServerInstance)
   @ LanguageServer C:\Users\alexa\.julia\packages\LanguageServer\jiDTR\src\languageserverinstance.jl:353
 [7] runserver(pipe_in::Base.PipeEndpoint, pipe_out::Base.PipeEndpoint, env_path::String, depot_path::String, err_handler::Nothing, symserver_store_path::Nothing)
   @ LanguageServer C:\Users\alexa\.julia\packages\LanguageServer\jiDTR\src\runserver.jl:46
 [8] runserver()
   @ LanguageServer C:\Users\alexa\.julia\packages\LanguageServer\jiDTR\src\runserver.jl:44
 [9] top-level scope
   @ none:1
</pre></details>

But then I followed your next advice and upgraded the extension to v3.7.0 — and happily got couple of hours of smooth work without any crash or error.

I would propose to keep this issue open for a week so that I could post here any updates on my side. If there will be nothing we  can consider the issue closed. Does it make sense to you?

**Comment by krassowski** [comment]
Hi @goryntsev, any updates on this one?
