### ISSUE TITLE
FileNotFoundError in web and server console

### ISSUE THREAD

**Issue by gumlooter** [krassowski/jupyterlab-lsp#64]
Hello,

Thank you for this extension! Started to working on it and have an issue:
Constantly getting an errors for accessing folders in my working directory. 

Can you please help?

```2019-10-23 10:10:27,426 UTC - ERROR - pyls_jsonrpc.endpoint - Failed to handle request 156
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/pyls_jsonrpc/endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "/opt/conda/lib/python3.7/site-packages/pyls_jsonrpc/endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "/opt/conda/lib/python3.7/site-packages/pyls_jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/opt/conda/lib/python3.7/site-packages/pyls/python_ls.py", line 311, in m_text_document__document_highlight
    return self.highlight(textDocument['uri'], position)
  File "/opt/conda/lib/python3.7/site-packages/pyls/python_ls.py", line 248, in highlight
    return flatten(self._hook('pyls_document_highlight', doc_uri, position=position)) or None
  File "/opt/conda/lib/python3.7/site-packages/pyls/python_ls.py", line 143, in _hook
    return hook_handlers(config=self.config, workspace=workspace, document=doc, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pluggy/manager.py", line 92, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pluggy/manager.py", line 335, in traced_hookexec
    return outcome.get_result()
  File "/opt/conda/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/opt/conda/lib/python3.7/site-packages/pluggy/callers.py", line 52, in from_call
    result = func()
  File "/opt/conda/lib/python3.7/site-packages/pluggy/manager.py", line 333, in <lambda>
    outcome = _Result.from_call(lambda: oldcall(hook, hook_impls, kwargs))
  File "/opt/conda/lib/python3.7/site-packages/pluggy/manager.py", line 86, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/opt/conda/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/opt/conda/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/opt/conda/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/opt/conda/lib/python3.7/site-packages/pyls/plugins/highlight.py", line 10, in pyls_document_highlight
    usages = document.jedi_script(position).usages()
  File "/opt/conda/lib/python3.7/site-packages/jedi/api/__init__.py", line 349, in usages
    return _usages(**kwargs)
  File "/opt/conda/lib/python3.7/site-packages/jedi/api/__init__.py", line 343, in _usages
    names = usages.usages(self._get_module(), tree_name)
  File "/opt/conda/lib/python3.7/site-packages/jedi/evaluate/usages.py", line 44, in usages
    for m in imports.get_modules_containing_name(module_context.evaluator, modules, search_name):
  File "/opt/conda/lib/python3.7/site-packages/jedi/evaluate/imports.py", line 565, in get_modules_containing_name
    for file_io, base_names in get_file_ios_to_check():
  File "/opt/conda/lib/python3.7/site-packages/jedi/evaluate/imports.py", line 557, in get_file_ios_to_check
    for file_io in check_directory(folder_io):
  File "/opt/conda/lib/python3.7/site-packages/jedi/evaluate/imports.py", line 520, in check_directory
    for file_name in folder_io.list():
  File "/opt/conda/lib/python3.7/site-packages/jedi/file_io.py", line 19, in list
    return os.listdir(self.path)
FileNotFoundError: [Errno 2] No such file or directory: '/education/yandex_praktikum/data_analyst'
```

![image](https://user-images.githubusercontent.com/217896/67382697-9712c500-f596-11e9-9657-acaf94feed34.png)

**Comment by krassowski** [comment]
It seems a duplicate of #33. Could you take a look at the other issue and highlight if there are any differences? (apologies that I have not released a new version yet, I am coming back to open-source contributions soon).

**Comment by gumlooter** [comment]
I can confirm that it's the same issue, sorry for posting a duplicate one. And it seems that it's not preventing extension to work properly. So I think this should be closed.
